version: '2'

networks:
  xos:
    external: true

services:
  synchronizer:
    image: xosproject/metronetwork-synchronizer
    networks:
      - xos
    #command: bash -c "sleep 86400"
    volumes:
        - /opt/cord_profile/node_key:/opt/cord_profile/node_key:ro
        - /opt/cord/build/platform-install/credentials/xosadmin@opencord.org:/opt/xos/services/metro-net/credentials/xosadmin@opencord.org
    external_links:
        - rcordbs_xos_redis_1:redis
    logging:
      driver: "json-file"
      options:
        max-size: "1000k"
        max-file: "5"