FROM xosproject/xos-synchronizer-base:candidate

ADD . /opt/xos/synchronizers/metro-net

ENTRYPOINT []

WORKDIR "/opt/xos/synchronizers/metro-net"


CMD bash -c "cd /opt/xos/synchronizers/metro-net; chmod 755 ./run-from-api.sh; ./run-from-api.sh"